language: c

env:
  global:
    # coverity token
    - secure: "THWKfpOxFbQxX8Oyg8qkNaPACdOqx4KljQYytfoSzEpGuWgDLzP5YUTq0jiZLm5BRCY3Vj+GbmYGUectpEJQ7UyccfxUipmuAMEpW1zcwzl5Pdspyz2O1rJVh5pb/qRss7VSmyieh8OJYyl5W//HGxsDU29rDPRP4oW6k2k3Zvs="
  matrix:
    # standard builds
    - CC=gcc
    - CC=clang
    # cross-compile using mingw
    - CC= PLATFORM="mingw32" ARCH="x86"
    - CC= PLATFORM="mingw32" ARCH="x86_64"

script: ./travis-ci-build.sh

before_install:
  - sudo apt-get update -qq
  - sudo apt-get remove -qq -y mingw32
  - sudo apt-get install -q -y mingw-w64

notifications:
  irc: "irc.freenode.org#spearmint"
  on_success: change
  on_failure: always

addons:
  coverity_scan:
    project:
      name: "zturtleman/mint-arena"
      description: "Build submitted via Travis CI"
    notification_email: zturtleman@gmail.com
    build_command_prepend: "make clean"
    build_command: "make release"
    branch_pattern: master
