language: c

env:
  global:
    # coverity token
    - secure: "THWKfpOxFbQxX8Oyg8qkNaPACdOqx4KljQYytfoSzEpGuWgDLzP5YUTq0jiZLm5BRCY3Vj+GbmYGUectpEJQ7UyccfxUipmuAMEpW1zcwzl5Pdspyz2O1rJVh5pb/qRss7VSmyieh8OJYyl5W//HGxsDU29rDPRP4oW6k2k3Zvs="
  matrix:
    # standard builds
    - CC=gcc
    - CC=clang
    # cross-compile using mingw
    - CC= PLATFORM="mingw32" ARCH="x86"
    - CC= PLATFORM="mingw32" ARCH="x86_64"

script: ./travis-ci-build.sh

sudo: false

addons:
  apt:
    packages:
      - binutils-mingw-w64-i686
      - gcc-mingw-w64-i686
      - binutils-mingw-w64-x86-64
      - gcc-mingw-w64-x86-64
      - gcc-mingw-w64
      - mingw-w64
  coverity_scan:
    project:
      name: "zturtleman/mint-arena"
    notification_email: zturtleman@gmail.com
    build_command_prepend: "make clean"
    build_command: "make release"
    branch_pattern: coverity_scan
